<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.5-beta1" />

    <PackageVersion Include="Syncfusion.Compression.Base" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Core.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Data.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.DataGridExport.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.DataSource.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Grid.Base" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Grid.Windows" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.GridCommon.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Licensing" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Pdf.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.SfDataGrid.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.SfInput.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.SfListView.WinForms" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Shared.Base" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Shared.Windows" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.SpellChecker.Base" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Tools.Base" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.Tools.Windows" Version="33.2.8" />
    <PackageVersion Include="Syncfusion.XlsIO.WinForms" Version="33.2.8" />
  </ItemGroup>
</Project>