using Syncfusion.WinForms.DataGrid;
using Syncfusion.WinForms.DataGrid.Enums;
using System;
using System.Collections.Generic;
using System.Data;
using System.Windows.Forms;

namespace Genesys.UI.Components.Controls.GridViews
{
    public static class GenesysGridConfigurator
    {
        public static void Configure(SfDataGrid grid)
        {
            if (grid == null)
                return;

            grid.AllowFiltering = true;
            grid.AllowSorting = true;
            grid.AllowTriStateSorting = true;
            grid.AllowGrouping = true;
            grid.ShowGroupDropArea = true;
            grid.AllowDraggingColumns = true;
            grid.AllowResizingColumns = true;
            grid.AllowResizingHiddenColumns = true;
            grid.AllowEditing = false;
            grid.AllowDeleting = false;
            grid.SelectionMode = GridSelectionMode.Extended;
            grid.NavigationMode = NavigationMode.Row;
            grid.AutoSizeColumnsMode = AutoSizeColumnsMode.AllCells;
        }

        public static void BindDataTable(
            SfDataGrid grid,
            DataTable table,
            IDictionary<string, string> numericFormats)
        {
            BindDataTable(grid, table, numericFormats, null);
        }

        public static void BindDataTable(
            SfDataGrid grid,
            DataTable table,
            IDictionary<string, string> numericFormats,
            GenesysGridViewLayout activeLayout)
        {
            if (grid == null || table == null)
                return;

            Configure(grid);
            grid.SuspendLayout();

            try
            {
                if (activeLayout != null && activeLayout.Columns != null && activeLayout.Columns.Count > 0)
                {
                    BindWithLayoutColumns(grid, table, numericFormats, activeLayout);
                }
                else
                {
                    BindWithAutoGeneratedColumns(grid, table, numericFormats);
                }
            }
            finally
            {
                grid.ResumeLayout(true);
            }
        }

        private static void BindWithAutoGeneratedColumns(
            SfDataGrid grid,
            DataTable table,
            IDictionary<string, string> numericFormats)
        {
            ResetBeforeDataSourceChange(grid, clearColumns: true);

            grid.AutoGenerateColumns = true;
            grid.DataSource = table;

            ApplyNumericFormats(grid, numericFormats);
        }

        private static void BindWithLayoutColumns(
            SfDataGrid grid,
            DataTable table,
            IDictionary<string, string> numericFormats,
            GenesysGridViewLayout layout)
        {
            ResetBeforeDataSourceChange(grid, clearColumns: true);

            grid.AutoGenerateColumns = false;

            AddLayoutColumns(grid, table, layout, numericFormats);

            grid.DataSource = table;

            ApplyNumericFormats(grid, numericFormats);
        }

        private static void AddLayoutColumns(
            SfDataGrid grid,
            DataTable table,
            GenesysGridViewLayout layout,
            IDictionary<string, string> numericFormats)
        {
            var added = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var savedColumn in SortedColumns(layout))
            {
                if (savedColumn == null || string.IsNullOrWhiteSpace(savedColumn.MappingName))
                    continue;

                if (!table.Columns.Contains(savedColumn.MappingName))
                    continue;

                GridColumn column = CreateColumnFromLayout(savedColumn, numericFormats);
                grid.Columns.Add(column);
                added.Add(savedColumn.MappingName);
            }

            foreach (DataColumn dataColumn in table.Columns)
            {
                if (added.Contains(dataColumn.ColumnName))
                    continue;

                grid.Columns.Add(new GridTextColumn
                {
                    MappingName = dataColumn.ColumnName,
                    HeaderText = dataColumn.ColumnName,
                    Visible = true
                });
            }
        }

        private static IEnumerable<GenesysGridColumnLayout> SortedColumns(GenesysGridViewLayout layout)
        {
            var columns = new List<GenesysGridColumnLayout>();

            if (layout == null || layout.Columns == null)
                return columns;

            columns.AddRange(layout.Columns);
            columns.Sort(delegate(GenesysGridColumnLayout a, GenesysGridColumnLayout b)
            {
                int ai = a == null ? int.MaxValue : a.DisplayIndex;
                int bi = b == null ? int.MaxValue : b.DisplayIndex;
                return ai.CompareTo(bi);
            });

            return columns;
        }

        private static GridColumn CreateColumnFromLayout(
            GenesysGridColumnLayout savedColumn,
            IDictionary<string, string> numericFormats)
        {
            string format = savedColumn.Format;

            if (numericFormats != null && !string.IsNullOrWhiteSpace(savedColumn.MappingName))
            {
                string numericFormat;
                if (numericFormats.TryGetValue(savedColumn.MappingName, out numericFormat) &&
                    !string.IsNullOrWhiteSpace(numericFormat))
                {
                    format = numericFormat;
                }
            }

            var column = new GridTextColumn
            {
                MappingName = savedColumn.MappingName,
                HeaderText = string.IsNullOrWhiteSpace(savedColumn.HeaderText)
                    ? savedColumn.MappingName
                    : savedColumn.HeaderText,
                Visible = savedColumn.Visible
            };

            if (savedColumn.Width > 0)
                column.Width = savedColumn.Width;

            if (!string.IsNullOrWhiteSpace(format))
                column.Format = format;

            return column;
        }

        private static void ResetBeforeDataSourceChange(SfDataGrid grid, bool clearColumns)
        {
            try
            {
                if (grid.TableSummaryRows != null)
                    grid.TableSummaryRows.Clear();
            }
            catch
            {
            }

            try
            {
                if (grid.GroupColumnDescriptions != null)
                    grid.GroupColumnDescriptions.Clear();
            }
            catch
            {
            }

            try
            {
                if (grid.SortColumnDescriptions != null)
                    grid.SortColumnDescriptions.Clear();
            }
            catch
            {
            }

            try
            {
                grid.DataSource = null;
            }
            catch
            {
            }

            if (!clearColumns)
                return;

            try
            {
                grid.Columns.Clear();
            }
            catch
            {
            }
        }

        public static void ApplyNumericFormats(SfDataGrid grid, IDictionary<string, string> numericFormats)
        {
            if (grid == null || numericFormats == null)
                return;

            foreach (var item in numericFormats)
                ApplyNumericFormat(grid, item.Key, item.Value);
        }

        public static void ApplyNumericFormat(SfDataGrid grid, string mappingName, string format)
        {
            if (grid == null || string.IsNullOrWhiteSpace(mappingName))
                return;

            GridColumn column = null;

            foreach (GridColumn currentColumn in grid.Columns)
            {
                if (string.Equals(currentColumn.MappingName, mappingName, StringComparison.OrdinalIgnoreCase))
                {
                    column = currentColumn;
                    break;
                }
            }

            if (column == null)
                return;

            column.Format = format;
            column.CellStyle.HorizontalAlignment = HorizontalAlignment.Right;
            column.HeaderStyle.HorizontalAlignment = HorizontalAlignment.Right;
        }
    }
}
