using Syncfusion.WinForms.DataGrid;
using Syncfusion.WinForms.DataGrid.Enums;
using System;
using System.Collections.Generic;
using System.Data;

namespace Genesys.UI.Components.Controls.GridViews
{
    public static class GridConfigurator
    {
        public static void Configure(SfDataGrid grid)
        {
            if (grid == null)
                return;

            grid.AllowFiltering = true;
            grid.AllowSorting = true;
            grid.AllowTriStateSorting = true;
            grid.AllowGrouping = true;
            grid.ShowGroupDropArea = true;
            grid.AllowDraggingColumns = true;
            grid.AllowResizingColumns = true;
            grid.AllowResizingHiddenColumns = true;
            grid.AllowEditing = false;
            grid.AllowDeleting = false;
            grid.SelectionMode = GridSelectionMode.Extended;
            grid.NavigationMode = NavigationMode.Row;
            grid.AutoSizeColumnsMode = AutoSizeColumnsMode.AllCells;
        }

        public static void BindDataTable(SfDataGrid grid, DataTable table)
        {
            BindDataTable(grid, table, null, false);
        }

        public static void BindDataTable(
            SfDataGrid grid,
            DataTable table,
            GridViewLayout activeLayout)
        {
            BindDataTable(grid, table, activeLayout, false);
        }

        public static void BindDataTable(
            SfDataGrid grid,
            DataTable table,
            GridViewLayout activeLayout,
            bool preserveRuntimeGridState)
        {
            if (grid == null || table == null)
                return;

            Configure(grid);
            grid.SuspendLayout();

            try
            {
                if (preserveRuntimeGridState &&
                    activeLayout != null &&
                    activeLayout.Columns != null &&
                    activeLayout.Columns.Count > 0)
                {
                    BindPreservingRuntimeState(grid, table, activeLayout);
                }
                else if (activeLayout != null && activeLayout.Columns != null && activeLayout.Columns.Count > 0)
                {
                    BindWithLayoutColumns(grid, table, activeLayout);
                }
                else
                {
                    BindWithAutoGeneratedColumns(grid, table);
                }
            }
            finally
            {
                grid.ResumeLayout(true);
            }
        }

        private static void BindPreservingRuntimeState(
            SfDataGrid grid,
            DataTable table,
            GridViewLayout layout)
        {
            /*
             * Se usa cuando la vista tiene cambios no guardados en runtime
             * (sort/filtro interno del grid/movimiento de columnas) y llega
             * un refresh desde el panel superior de filtros.
             *
             * No limpiamos columnas, sorts, groups, summaries ni filtros del SfDataGrid.
             * Solo cambiamos el DataSource para conservar el estado visual actual.
             *
             * Importante: aquí NO se aplica ningún formato global.
             * La única fuente de verdad del formato es GridColumn.Format/layout.Columns[].Format.
             */
            grid.AutoGenerateColumns = false;

            if (grid.Columns == null || grid.Columns.Count == 0)
                AddLayoutColumns(grid, table, layout);

            grid.DataSource = table;
        }

        private static void BindWithAutoGeneratedColumns(SfDataGrid grid, DataTable table)
        {
            ResetBeforeDataSourceChange(grid, clearColumns: true);

            grid.AutoGenerateColumns = true;
            grid.DataSource = table;
        }

        private static void BindWithLayoutColumns(
            SfDataGrid grid,
            DataTable table,
            GridViewLayout layout)
        {
            ResetBeforeDataSourceChange(grid, clearColumns: true);

            grid.AutoGenerateColumns = false;
            AddLayoutColumns(grid, table, layout);
            grid.DataSource = table;
        }

        private static void AddLayoutColumns(
            SfDataGrid grid,
            DataTable table,
            GridViewLayout layout)
        {
            var added = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var savedColumn in SortedColumns(layout))
            {
                if (savedColumn == null || string.IsNullOrWhiteSpace(savedColumn.MappingName))
                    continue;

                if (!table.Columns.Contains(savedColumn.MappingName))
                    continue;

                DataColumn dataColumn = table.Columns[savedColumn.MappingName];
                GridColumn column = CreateColumnFromLayout(savedColumn, dataColumn);
                grid.Columns.Add(column);
                added.Add(savedColumn.MappingName);
            }

            foreach (DataColumn dataColumn in table.Columns)
            {
                if (added.Contains(dataColumn.ColumnName))
                    continue;

                grid.Columns.Add(CreateColumnFromDataColumn(dataColumn));
            }
        }

        private static IEnumerable<GenesysGridColumnLayout> SortedColumns(GridViewLayout layout)
        {
            var columns = new List<GenesysGridColumnLayout>();

            if (layout == null || layout.Columns == null)
                return columns;

            columns.AddRange(layout.Columns);
            columns.Sort(delegate(GenesysGridColumnLayout a, GenesysGridColumnLayout b)
            {
                int ai = a == null ? int.MaxValue : a.DisplayIndex;
                int bi = b == null ? int.MaxValue : b.DisplayIndex;
                return ai.CompareTo(bi);
            });

            return columns;
        }

        private static GridColumn CreateColumnFromLayout(
            GenesysGridColumnLayout savedColumn,
            DataColumn dataColumn)
        {
            GridColumn column = CreateColumnForDataType(
                dataColumn,
                savedColumn.Format);

            column.MappingName = savedColumn.MappingName;
            column.HeaderText = string.IsNullOrWhiteSpace(savedColumn.HeaderText)
                ? savedColumn.MappingName
                : savedColumn.HeaderText;
            column.Visible = savedColumn.Visible;

            // Asignar siempre, incluso vacío.
            // Vacío significa "Automático" para Syncfusion; no debe heredar formato runtime.
            column.Format = savedColumn.Format ?? string.Empty;

            if (savedColumn.Width > 0)
                column.Width = savedColumn.Width;

            return column;
        }

        private static GridColumn CreateColumnFromDataColumn(DataColumn dataColumn)
        {
            GridColumn column = CreateColumnForDataType(dataColumn, null);

            column.MappingName = dataColumn.ColumnName;
            column.HeaderText = dataColumn.ColumnName;
            column.Visible = true;
            column.Format = string.Empty;

            return column;
        }

        private static GridColumn CreateColumnForDataType(
            DataColumn dataColumn,
            string explicitFormat)
        {
            Type dataType = GetNonNullableType(dataColumn == null ? null : dataColumn.DataType);

            if (IsDateType(dataType))
                return new GridDateTimeColumn();

            if (IsNumericType(dataType) || LooksLikeNumericFormat(explicitFormat))
                return new GridNumericColumn();

            return new GridTextColumn();
        }

        private static Type GetNonNullableType(Type type)
        {
            if (type == null)
                return null;

            return Nullable.GetUnderlyingType(type) ?? type;
        }

        private static bool IsDateType(Type type)
        {
            return type == typeof(DateTime);
        }

        private static bool IsNumericType(Type type)
        {
            if (type == null)
                return false;

            return type == typeof(byte) ||
                   type == typeof(sbyte) ||
                   type == typeof(short) ||
                   type == typeof(ushort) ||
                   type == typeof(int) ||
                   type == typeof(uint) ||
                   type == typeof(long) ||
                   type == typeof(ulong) ||
                   type == typeof(float) ||
                   type == typeof(double) ||
                   type == typeof(decimal);
        }

        private static bool LooksLikeNumericFormat(string format)
        {
            if (string.IsNullOrWhiteSpace(format))
                return false;

            string value = format.Trim();

            return value.StartsWith("N", StringComparison.OrdinalIgnoreCase) ||
                   value.StartsWith("C", StringComparison.OrdinalIgnoreCase) ||
                   value.StartsWith("P", StringComparison.OrdinalIgnoreCase) ||
                   value.StartsWith("F", StringComparison.OrdinalIgnoreCase);
        }

        private static void ResetBeforeDataSourceChange(SfDataGrid grid, bool clearColumns)
        {
            try
            {
                if (grid.TableSummaryRows != null)
                    grid.TableSummaryRows.Clear();
            }
            catch
            {
            }

            try
            {
                if (grid.GroupColumnDescriptions != null)
                    grid.GroupColumnDescriptions.Clear();
            }
            catch
            {
            }

            try
            {
                if (grid.SortColumnDescriptions != null)
                    grid.SortColumnDescriptions.Clear();
            }
            catch
            {
            }

            try
            {
                grid.DataSource = null;
            }
            catch
            {
            }

            if (!clearColumns)
                return;

            try
            {
                grid.Columns.Clear();
            }
            catch
            {
            }
        }
    }
}
